# https://taskfile.dev

version: '3'

vars:
  FUNCTION_NAME: mugen-shunkan-eisakubun

tasks:
  zip:
    desc: lambdaにデプロイするためにPythonのソースコードをzipに固めます
    dir: work
    cmds:
      - cp ../mugen-shunkan-eisakubun.py ./
      - poetry export -f requirements.txt --output requirements.txt
      - poetry run pip install -r requirements.txt -t .
      - zip -r function.zip *
      - mv function.zip ../
      - cd ../ && rm -rf work

  rm:
    desc: ビルドとデプロイのために作成したファイルを削除します
    cmds:
      - rm function.zip

  update:
    desc: update lambda
    cmds:
      - aws lambda update-function-code --function-name {{.FUNCTION_NAME}} --zip-file fileb://function.zip

  deploy:
    desc: deploy lambda
    cmds:
      - task: zip
      - task: update
      - task: rm

  clean:
    desc: rm & destroy
    cmds:
      - task: rm
      - task: destroy

  apply:
    desc: terraform apply
    cmds:
      - task: zip
      - terraform apply
      - task: rm